name: Build HVCC for Mac

inputs:
  pd-file:
    description: 'Path to the .pd file to serve as input to hvcc'
    required: true
  output-patch-name:
    description: 'Output patch name (-n argument to hvcc)'
    required: true
  search-paths:
    description: 'Any search paths to use for including supplementary pd functionality (-p argument to hvcc)'
    required: false
runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v1
  - name: Run debug commands (pwd)
    shell: bash
    run: pwd
  - name: Run debug commands (ls)
    shell: bash
    run: ls -R .
  - name: Run hvcc
    uses: michaelpace/run-hvcc-action@7de02972eaea31540d8a266d8748c97dcec3b19a
    with:
      pd-file: ${{ inputs.pd-file }}
      search-paths: ${{ inputs.search-paths }}
      generator: unity
      output-patch-name: ${{ inputs.output-patch-name }}
  - name: Run xcodebuild for Intel
    shell: bash
    run: xcodebuild -project HeavyBuild/${{ inputs.output-patch-name }}/unity/xcode/Hv_${{ inputs.output-patch-name }}_Unity.xcodeproj -arch x86_64 -alltargets
  - name: Upload Intel results
    uses: actions/upload-artifact@v3
    with:
      name: hvcc-build-mac-intel-unity
      path: |
        HeavyBuild/${{ inputs.output-patch-name }}/unity/build/macos/x86_64/Release/
  - name: Run xcodebuild for Silicon
    shell: bash
    run: xcodebuild -project HeavyBuild/${{ inputs.output-patch-name }}/unity/xcode/Hv_${{ inputs.output-patch-name }}_Unity.xcodeproj -arch arm64e -alltargets
  - name: Upload Silicon results
    uses: actions/upload-artifact@v3
    with:
      name: hvcc-build-mac-silicon-unity
      path: |
        HeavyBuild/${{ inputs.output-patch-name }}/unity/build/macos/arm64e/Release/
